// Code generated by Codex prompt: VNPrider Layer 1
// DO NOT EDIT MANUALLY
package crypto

import "testing"

func TestComputeSHA3(t *testing.T) {
	_ = ComputeSHA3([]byte("test"))
}

func TestComputeRIPEMD160(t *testing.T) {
	_ = ComputeRIPEMD160([]byte("test"))
}
