// Code generated by Codex prompt: VNPrider Layer 1
// DO NOT EDIT MANUALLY
package crypto

import "testing"

func TestSignVerify(t *testing.T) {
	priv, pub, _ := GenerateKeypair()
	msg := []byte("hello")
	sig, _ := Sign(priv, msg)
	Verify(pub, msg, sig)
}
