// Code generated by Codex prompt: VNPrider Layer 1
// DO NOT EDIT MANUALLY
package network

import "testing"

func TestNewHost(t *testing.T) {
	cfg := &P2PConfig{ListenPort: 0, BootstrapPeers: []string{}}
	NewHost(cfg)
}
