// Code generated by Codex prompt: VNPrider Layer 1
// DO NOT EDIT MANUALLY
package storage

import (
	"encoding/json"
	"errors"
	"os"
	"sync"

	"github.com/devprosvn/VNPrider/pkg/ledger"
)

// LevelDBStore implements BlockStore and StateStore

type LevelDBStore struct {
	mu     sync.RWMutex
	blocks map[uint64]*ledger.Block
	state  map[string][]byte
}

func NewLevelDBStore(path string) (*LevelDBStore, error) {
	return &LevelDBStore{
		blocks: make(map[uint64]*ledger.Block),
		state:  make(map[string][]byte),
	}, nil
}

func (l *LevelDBStore) SaveBlock(b *ledger.Block) error {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.blocks[b.Header.Height] = b
	return nil
}

func (l *LevelDBStore) GetBlock(height uint64) (*ledger.Block, error) {
	l.mu.RLock()
	defer l.mu.RUnlock()
	b, ok := l.blocks[height]
	if !ok {
		return nil, errors.New("block not found")
	}
	return b, nil
}

func (l *LevelDBStore) SetState(key string, value []byte) error {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.state[key] = value
	return nil
}

func (l *LevelDBStore) GetState(key string) ([]byte, error) {
	l.mu.RLock()
	defer l.mu.RUnlock()
	v, ok := l.state[key]
	if !ok {
		return nil, errors.New("state not found")
	}
	return v, nil
}

// ExportSnapshot exports database snapshot
func (l *LevelDBStore) ExportSnapshot(path string) error {
	l.mu.RLock()
	defer l.mu.RUnlock()
	data, err := json.Marshal(l)
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

// ImportSnapshot imports database snapshot
func (l *LevelDBStore) ImportSnapshot(path string) error {
	l.mu.Lock()
	defer l.mu.Unlock()
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	tmp := LevelDBStore{}
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}
	l.blocks = tmp.blocks
	l.state = tmp.state
	return nil
}
