// Code generated by Codex prompt: VNPrider Layer 1
// DO NOT EDIT MANUALLY
package storage

import "testing"

func TestNewLevelDBStore(t *testing.T) {
	_, _ = NewLevelDBStore("/tmp/vnprider-test")
}
