name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'
      - name: Build
        run: bash scripts/build.sh
      - name: Test
        run: bash scripts/test.sh
